# Generated by Django 5.0 on 2023-12-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0002_computer_delete_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/{id}', verbose_name='Photo'),
        ),
    ]
