# Generated by Django 5.0 on 2023-12-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0004_alter_computer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/{id}-{random.randint(0, 200)}', verbose_name='Photo'),
        ),
    ]
