# Generated by Django 5.0 on 2023-12-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0005_alter_computer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Photo'),
        ),
    ]
