# Generated by Django 4.2.5 on 2023-12-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0006_alter_computer_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'ordering': ['-id'], 'verbose_name': 'Компьютер', 'verbose_name_plural': 'Компьютеры'},
        ),
    ]
