# Generated by Django 4.2.5 on 2023-12-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0008_alter_category_options_alter_computer_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='configuration',
            field=models.TextField(max_length=700),
        ),
    ]
