# Generated by Django 4.2.5 on 2023-12-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0009_alter_computer_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='configuration',
            field=models.TextField(blank=True, default='The configuration is not filled in', max_length=1000),
        ),
    ]
