# Generated by Django 4.2.5 on 2023-12-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0010_alter_computer_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='details',
            field=models.TextField(blank=True, default='A detailed description has not yet been added'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pc.category'),
        ),
    ]
